### ISSUE TITLE
Recommend Additional RLS or Security Definer

### ISSUE THREAD

**Issue by zineanteoh** [alanagoyal/alanagoyal#31]
## Problem
Currently, anyone is able to modify the client side request to select every rows in the `notes` table. 

Here is a minimal curl command to do so: 
```
curl 'https://blablabla.supabase.co/rest/v1/notes?select=*' -H 'apikey: <insert-client-side-api-key>'
```

## Proposed Solution
In most apps, there should be additional RLS to only allow users to query their own rows. 
But since this is an app requiring no authenticated users, perhaps something like [this StackOverFlow post](https://stackoverflow.com/a/74284507) could suffice as a solution? What do you think? 

<img width="400" alt="image" src="https://github.com/alanagoyal/alanagoyal/assets/58854510/cb041803-c46c-4124-9804-e4e6732b5f9f">

**Comment by alanagoyal** [comment]
working on this now! thanks for pointing it out :)

**Comment by alanagoyal** [comment]
just merged this change!
